title       = "monokai"
author      = "mjhd"
version     = "0.0.0.1"
website     = "http://devlion.net"

[light-bg-style]
Cursor                       = "color:#272822;background-color:#f8f8f0;"
Select                       = "background-color:#49483e;"
CursorLine                   = "background-color:#3c3d37;"
CursorColumn                 = "background-color:#3c3d37;"
ColorColumn                  = "background-color:#3c3d37;"
LineNumber                   = "color:#90908a;background-color:#3c3d37;"
MatchParen                   = "color:#f92672;font:underline;"
Search                       = "font:underline;"
Directory                    = "color:#ae81ff;"
Folded                       = "color:#75715e;background-color:#272822;"
SignColumn                   = "background-color:#3c3d37;"
Default                      = "color:#f8f8f2;background-color:#272822;"
Boolean                      = "color:#ae81ff;"
Character                    = "color:#ae81ff;"
Comment                      = "color:#75715e;"
Conditional                  = "color:#f92672;"
Constant                     = ""
Define                       = "color:#f92672;"
DiffAdd                      = "color:#f8f8f2;background-color:#46830c;font:bold;"
DiffDelete                   = "color:#8b0807;"
DiffChange                   = "color:#f8f8f2;background-color:#243955;"
DiffText                     = "color:#f8f8f2;background-color:#204a87;font:bold;"
ErrorMsg                     = "color:#f8f8f0;background-color:#f92672;"
WarningMsg                   = "color:#f8f8f0;background-color:#f92672;"
Float                        = "color:#ae81ff;"
Function                     = "color:#a6e22e;"
Identifier                   = "color:#66d9ef;font:italic;"
Keyword                      = "color:#f92672;"
Label                        = "color:#e6db74;"
NonText                      = "color:#49483e;background-color:#31322c;"
Number                       = "color:#ae81ff;"
Operator                     = "color:#f92672;"
PreProc                      = "color:#f92672;"
Special                      = "color:#f8f8f2;"
SpecialKey                   = "color:#49483e;background-color:#3c3d37;"
Statement                    = "color:#f92672;"
StorageClass                 = "color:#66d9ef;font:italic;"
String                       = "color:#e6db74;"
Tag                          = "color:#f92672;"
Title                        = "color:#f8f8f2;font:bold;"
Todo                         = "color:#75715e;font:old;"
Type                         = "color:#f92672;"
Underlined                   = "font:underline;"
rubyClass                    = "color:#f92672;"
rubyFunction                 = "color:#a6e22e;"
rubyInterpolationDelimiter   = ""
rubySymbol                   = "color:#ae81ff;"
rubyConstant                 = "color:#66d9ef;font:italic;"
rubyStringDelimiter          = "color:#e6db74;"
rubyBlockParameter           = "color:#fd971f;font:italic;"
rubyInstanceVariable         = ""
rubyInclude                  = "color:#f92672;"
rubyGlobalVariable           = ""
rubyRegexp                   = "color:#e6db74;"
rubyRegexpDelimiter          = "color:#e6db74;"
rubyEscape                   = "color:#ae81ff;"
rubyControl                  = "color:#f92672;"
rubyClassVariable            = ""
rubyOperator                 = "color:#f92672;"
rubyException                = "color:#f92672;"
rubyPseudoVariable           = ""
rubyRailsUserClass           = "color:#66d9ef;font:italic;"
rubyRailsARAssociationMethod = "color:#66d9ef;"
rubyRailsARMethod            = "color:#66d9ef;"
rubyRailsRenderMethod        = "color:#66d9ef;"
rubyRailsMethod              = "color:#66d9ef;"
erubyDelimiter               = ""
erubyComment                 = "color:#75715e;"
erubyRailsMethod             = "color:#66d9ef;"
htmlTag                      = ""
htmlEndTag                   = "color:#a6e22e;"
htmlTagName                  = ""
htmlArg                      = ""
htmlSpecialChar              = "color:#ae81ff;"
javaScriptFunction           = "color:#66d9ef;font:italic;"
javaScriptRailsFunction      = "color:#66d9ef;"
javaScriptBraces             = ""
yamlKey                      = "color:#f92672;"
yamlAnchor                   = ""
yamlAlias                    = ""
yamlDocumentHeader           = "color:#e6db74;"
cssURL                       = "color:#fd971f;font:italic;"
cssFunctionName              = "color:#66d9ef;"
cssColor                     = "color:#ae81ff;"
cssPseudoClassId             = "color:#a6e22e;"
cssClassName                 = "color:#a6e22e;"
cssValueLength               = "color:#ae81ff;"
cssCommonAttr                = "color:#66d9ef;"
cssBraces                    = ""

[dark-bg-style]
Cursor                       = "color:#272822;background-color:#f8f8f0;"
Visual                       = "background-color:#49483e;"
CursorLine                   = "background-color:#3c3d37;"
CursorColumn                 = "background-color:#3c3d37;"
ColorColumn                  = "background-color:#3c3d37;"
LineNumber                   = "color:#90908a;background-color:#3c3d37;"
VertSplit                    = "color:#64645e;background-color:#64645e;"
MatchParen                   = "color:#f92672;font:underline;"
StatusLine                   = "color:#f8f8f2;background-color:#64645e;font:bold;"
StatusLineNC                 = "color:#f8f8f2;background-color:#64645e;"
Pmenu                        = ""
PmenuSel                     = "background-color:#49483e;"
IncSearch                    = "color:#272822;background-color:#e6db74;"
Search                       = "font:underline;"
Directory                    = "color:#ae81ff;"
Folded                       = "color:#75715e;background-color:#272822;"
SignColumn                   = "background-color:#3c3d37;"
Default                      = "color:#f8f8f2;background-color:#272822;"
Boolean                      = "color:#ae81ff;"
Character                    = "color:#ae81ff;"
Comment                      = "color:#75715e;"
Conditional                  = "color:#f92672;"
Constant                     = ""
Define                       = "color:#f92672;"
DiffAdd                      = "color:#f8f8f2;background-color:#46830c;font:bold;"
DiffDelete                   = "color:#8b0807;"
DiffChange                   = "color:#f8f8f2;background-color:#243955;"
DiffText                     = "color:#f8f8f2;background-color:#204a87;font:bold;"
ErrorMsg                     = "color:#f8f8f0;background-color:#f92672;"
WarningMsg                   = "color:#f8f8f0;background-color:#f92672;"
Float                        = "color:#ae81ff;"
Function                     = "color:#a6e22e;"
Identifier                   = "color:#66d9ef;font:italic;"
Keyword                      = "color:#f92672;"
Label                        = "color:#e6db74;"
NonText                      = "color:#49483e;background-color:#31322c;"
Number                       = "color:#ae81ff;"
Operator                     = "color:#f92672;"
PreProc                      = "color:#f92672;"
Special                      = "color:#f8f8f2;"
SpecialKey                   = "color:#49483e;background-color:#3c3d37;"
Statement                    = "color:#f92672;"
StorageClass                 = "color:#66d9ef;font:italic;"
String                       = "color:#e6db74;"
Tag                          = "color:#f92672;"
Title                        = "color:#f8f8f2;font:bold;"
Todo                         = "color:#75715e;font:old;"
Type                         = "color:#f92672;"
Underlined                   = "font:underline;"
rubyClass                    = "color:#f92672;"
rubyFunction                 = "color:#a6e22e;"
rubyInterpolationDelimiter   = ""
rubySymbol                   = "color:#ae81ff;"
rubyConstant                 = "color:#66d9ef;font:italic;"
rubyStringDelimiter          = "color:#e6db74;"
rubyBlockParameter           = "color:#fd971f;font:italic;"
rubyInstanceVariable         = ""
rubyInclude                  = "color:#f92672;"
rubyGlobalVariable           = ""
rubyRegexp                   = "color:#e6db74;"
rubyRegexpDelimiter          = "color:#e6db74;"
rubyEscape                   = "color:#ae81ff;"
rubyControl                  = "color:#f92672;"
rubyClassVariable            = ""
rubyOperator                 = "color:#f92672;"
rubyException                = "color:#f92672;"
rubyPseudoVariable           = ""
rubyRailsUserClass           = "color:#66d9ef;font:italic;"
rubyRailsARAssociationMethod = "color:#66d9ef;"
rubyRailsARMethod            = "color:#66d9ef;"
rubyRailsRenderMethod        = "color:#66d9ef;"
rubyRailsMethod              = "color:#66d9ef;"
erubyDelimiter               = ""
erubyComment                 = "color:#75715e;"
erubyRailsMethod             = "color:#66d9ef;"
htmlTag                      = ""
htmlEndTag                   = "color:#a6e22e;"
htmlTagName                  = ""
htmlArg                      = ""
htmlSpecialChar              = "color:#ae81ff;"
javaScriptFunction           = "color:#66d9ef;font:italic;"
javaScriptRailsFunction      = "color:#66d9ef;"
javaScriptBraces             = ""
yamlKey                      = "color:#f92672;"
yamlAnchor                   = ""
yamlAlias                    = ""
yamlDocumentHeader           = "color:#e6db74;"
cssURL                       = "color:#fd971f;font:italic;"
cssFunctionName              = "color:#66d9ef;"
cssColor                     = "color:#ae81ff;"
cssPseudoClassId             = "color:#a6e22e;"
cssClassName                 = "color:#a6e22e;"
cssValueLength               = "color:#ae81ff;"
cssCommonAttr                = "color:#66d9ef;"
cssBraces                    = ""
